export const COMPLAINT_STATUSES = ['OPEN', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED'];

export const COMPLAINT_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

export const ASSIGNMENT_STATUSES = ['ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED'];

export const ROLES = { CUSTOMER: 'CUSTOMER', ENGINEER: 'ENGINEER', ADMIN: 'ADMIN' };
